/** @format */

export enum actionTypeKeys {
	ADD_TO_CART = "ADD_TO_CART",
	REMOVE_FROM_CART = "REMOVE_FROM_CART",
	CLEAR_CART = "CLEAR_CART",
	CREATE_ORDER = "CREATE_ORDER",
	ACCEPT_ORDER_TO_KITCHEN = "ACCEPT_ORDER_TO_KITCHEN",
	MARK_ORDER_READY = "MARK_ORDER_READY",
	COMPLETE_ORDER = "COMPLETE_ORDER",
	TOGGLE_CART = "TOGGLE_CART",
}